package models

import "time"

type Well struct {
	DataSource                string    `json:"dataSource"`
	Abstract                  string    `json:"abstract"`
	AcreSpacing               float64   `json:"acreSpacing"`
	AllocationType            string    `json:"allocationType"`
	Api10                     string    `json:"api10"`
	Api12                     string    `json:"api12"`
	Api14                     string    `json:"api14"`
	AriesID                   string    `json:"ariesId"`
	Azimuth                   float64   `json:"azimuth"`
	Basin                     string    `json:"basin"`
	Bg                        float64   `json:"bg"`
	Block                     string    `json:"block"`
	Bo                        float64   `json:"bo"`
	BubblePointPress          float64   `json:"bubblePointPress"`
	CasingID                  float64   `json:"casingId"`
	ChokeSize                 float64   `json:"chokeSize"`
	ChosenID                  string    `json:"chosenID"`
	ChosenKeyID               string    `json:"chosenKeyID"`
	CompletionDesign          string    `json:"completionDesign"`
	CompletionEndDate         time.Time `json:"completionEndDate"`   // You can replace string with time.Time if you'll parse dates
	CompletionStartDate       time.Time `json:"completionStartDate"` // You can replace string with time.Time if you'll parse dates
	Country                   string    `json:"country"`
	County                    string    `json:"county"`
	CurrentOperator           string    `json:"currentOperator"`
	CurrentOperatorAlias      string    `json:"currentOperatorAlias"`
	CurrentOperatorCode       string    `json:"currentOperatorCode"`
	CurrentOperatorTicker     string    `json:"currentOperatorTicker"`
	CustomBool0               bool      `json:"customBool0"`
	CustomBool1               bool      `json:"customBool1"`
	CustomBool2               bool      `json:"customBool2"`
	CustomBool3               bool      `json:"customBool3"`
	CustomBool4               bool      `json:"customBool4"`
	CustomDate0               string    `json:"customDate0"` // You can replace string with time.Time if you'll parse dates
	CustomDate1               string    `json:"customDate1"` // ...
	CustomDate2               string    `json:"customDate2"`
	CustomDate3               string    `json:"customDate3"`
	CustomDate4               string    `json:"customDate4"`
	CustomDate5               string    `json:"customDate5"`
	CustomDate6               string    `json:"customDate6"`
	CustomDate7               string    `json:"customDate7"`
	CustomDate8               string    `json:"customDate8"`
	CustomDate9               string    `json:"customDate9"`
	CustomNumber0             float64   `json:"customNumber0"`
	CustomNumber1             float64   `json:"customNumber1"`
	CustomNumber10            float64   `json:"customNumber10"`
	CustomNumber11            float64   `json:"customNumber11"`
	CustomNumber12            float64   `json:"customNumber12"`
	CustomNumber13            float64   `json:"customNumber13"`
	CustomNumber14            float64   `json:"customNumber14"`
	CustomNumber15            float64   `json:"customNumber15"`
	CustomNumber16            float64   `json:"customNumber16"`
	CustomNumber17            float64   `json:"customNumber17"`
	CustomNumber18            float64   `json:"customNumber18"`
	CustomNumber19            float64   `json:"customNumber19"`
	CustomNumber2             float64   `json:"customNumber2"`
	CustomNumber3             float64   `json:"customNumber3"`
	CustomNumber4             float64   `json:"customNumber4"`
	CustomNumber5             float64   `json:"customNumber5"`
	CustomNumber6             float64   `json:"customNumber6"`
	CustomNumber7             float64   `json:"customNumber7"`
	CustomNumber8             float64   `json:"customNumber8"`
	CustomNumber9             float64   `json:"customNumber9"`
	CustomString0             string    `json:"customString0"`
	CustomString1             string    `json:"customString1"`
	CustomString10            string    `json:"customString10"`
	CustomString11            string    `json:"customString11"`
	CustomString12            string    `json:"customString12"`
	CustomString13            string    `json:"customString13"`
	CustomString14            string    `json:"customString14"`
	CustomString15            string    `json:"customString15"`
	CustomString16            string    `json:"customString16"`
	CustomString17            string    `json:"customString17"`
	CustomString18            string    `json:"customString18"`
	CustomString19            string    `json:"customString19"`
	CustomString2             string    `json:"customString2"`
	CustomString3             string    `json:"customString3"`
	CustomString4             string    `json:"customString4"`
	CustomString5             string    `json:"customString5"`
	CustomString6             string    `json:"customString6"`
	CustomString7             string    `json:"customString7"`
	CustomString8             string    `json:"customString8"`
	CustomString9             string    `json:"customString9"`
	DataSourceCustomName      string    `json:"dataSourceCustomName"`
	DateRigRelease            time.Time `json:"dateRigRelease"` // time.Time if you'll parse dates
	DewPointPress             float64   `json:"dewPointPress"`
	DistanceFromBaseOfZone    float64   `json:"distanceFromBaseOfZone"`
	DistanceFromTopOfZone     float64   `json:"distanceFromTopOfZone"`
	District                  string    `json:"district"`
	DrainageArea              float64   `json:"drainageArea"`
	DrillEndDate              time.Time `json:"drillEndDate"`   // time.Time if you'll parse dates
	DrillStartDate            time.Time `json:"drillStartDate"` // time.Time if you'll parse dates
	DrillinginfoID            string    `json:"drillinginfoId"`
	Elevation                 float64   `json:"elevation"`
	ElevationType             string    `json:"elevationType"`
	Field                     string    `json:"field"`
	FirstAdditiveVolume       float64   `json:"firstAdditiveVolume"`
	FirstClusterCount         float64   `json:"firstClusterCount"`
	FirstFluidVolume          float64   `json:"firstFluidVolume"`
	FirstFracVendor           string    `json:"firstFracVendor"`
	FirstMaxInjectionPressure float64   `json:"firstMaxInjectionPressure"`
	FirstMaxInjectionRate     float64   `json:"firstMaxInjectionRate"`
	FirstProdDate             time.Time `json:"firstProdDate"` // time.Time if you'll parse dates
	FirstPropWeight           float64   `json:"firstPropWeight"`
	FirstStageCount           float64   `json:"firstStageCount"`
	FirstTestFlowTbgPress     float64   `json:"firstTestFlowTbgPress"`
	FirstTestGasVol           float64   `json:"firstTestGasVol"`
	FirstTestGor              float64   `json:"firstTestGor"`
	FirstTestOilVol           float64   `json:"firstTestOilVol"`
	FirstTestWaterVol         float64   `json:"firstTestWaterVol"`
	FirstTreatmentType        string    `json:"firstTreatmentType"`
	FlowPath                  string    `json:"flowPath"`
	FluidType                 string    `json:"fluidType"`
	FootageInLandingZone      float64   `json:"footageInLandingZone"`
	FormationThicknessMean    float64   `json:"formationThicknessMean"`
	FractureConductivity      float64   `json:"fractureConductivity"`
	GasAnalysisDate           time.Time `json:"gasAnalysisDate"` // time.Time if you'll parse dates
	GasC1                     float64   `json:"gasC1"`
	GasC2                     float64   `json:"gasC2"`
	GasC3                     float64   `json:"gasC3"`
	GasCo2                    float64   `json:"gasCo2"`
	GasGatherer               string    `json:"gasGatherer"`
	GasH2                     float64   `json:"gasH2"`
	GasH2o                    float64   `json:"gasH2o"`
	GasH2s                    float64   `json:"gasH2s"`
	GasHe                     float64   `json:"gasHe"`
	GasIc4                    float64   `json:"gasIc4"`
	GasIc5                    float64   `json:"gasIc5"`
	GasN2                     float64   `json:"gasN2"`
	GasNc10                   float64   `json:"gasNc10"`
	GasNc4                    float64   `json:"gasNc4"`
	GasNc5                    float64   `json:"gasNc5"`
	GasNc6                    float64   `json:"gasNc6"`
	GasNc7                    float64   `json:"gasNc7"`
	GasNc8                    float64   `json:"gasNc8"`
	GasNc9                    float64   `json:"gasNc9"`
	GasO2                     float64   `json:"gasO2"`
	GasSpecificGravity        float64   `json:"gasSpecificGravity"`
	GrossPerforatedInterval   float64   `json:"grossPerforatedInterval"`
	GroundElevation           float64   `json:"groundElevation"`
	HeelLatitude              float64   `json:"heelLatitude"`
	HeelLongitude             float64   `json:"heelLongitude"`
	HoleDirection             string    `json:"holeDirection"`
	HorizontalSpacing         float64   `json:"horizontalSpacing"`
	HzWellSpacingAnyZone      float64   `json:"hzWellSpacingAnyZone"`
	HzWellSpacingSameZone     float64   `json:"hzWellSpacingSameZone"`
	ID                        string    `json:"id"`
	IhsID                     string    `json:"ihsId"`
	InitialRespress           float64   `json:"initialRespress"`
	InitialRestemp            float64   `json:"initialRestemp"`
	LandingZone               string    `json:"landingZone"`
	LandingZoneBase           float64   `json:"landingZoneBase"`
	LandingZoneTop            float64   `json:"landingZoneTop"`
	LateralLength             float64   `json:"lateralLength"`
	LeaseName                 string    `json:"leaseName"`
	LeaseNumber               string    `json:"leaseNumber"`
	LowerPerforation          float64   `json:"lowerPerforation"`
	MatrixPermeability        float64   `json:"matrixPermeability"`
	MeasuredDepth             float64   `json:"measuredDepth"`
	NglGatherer               string    `json:"nglGatherer"`
	NumTreatmentRecords       float64   `json:"numTreatmentRecords"`
	OilApiGravity             float64   `json:"oilApiGravity"`
	OilGatherer               string    `json:"oilGatherer"`
	OilSpecificGravity        float64   `json:"oilSpecificGravity"`
	PadName                   string    `json:"padName"`
	ParentChildAnyZone        string    `json:"parentChildAnyZone"`
	ParentChildSameZone       string    `json:"parentChildSameZone"`
	PercentInZone             float64   `json:"percentInZone"`
	PerfLateralLength         float64   `json:"perfLateralLength"`
	PermitDate                time.Time `json:"permitDate"` // time.Time if you'll parse dates
	PhdwinID                  string    `json:"phdwinId"`
	Play                      string    `json:"play"`
	Porosity                  float64   `json:"porosity"`
	PreviousOperator          string    `json:"previousOperator"`
	PreviousOperatorAlias     string    `json:"previousOperatorAlias"`
	PreviousOperatorCode      string    `json:"previousOperatorCode"`
	PreviousOperatorTicker    string    `json:"previousOperatorTicker"`
	PrimaryProduct            string    `json:"primaryProduct"`
	PrmsReservesCategory      string    `json:"prmsReservesCategory"`
	PrmsReservesSubCategory   string    `json:"prmsReservesSubCategory"`
	PrmsResourcesClass        string    `json:"prmsResourcesClass"`
	ProductionMethod          string    `json:"productionMethod"`

	ProppantMeshSize           string    `json:"proppantMeshSize"`
	ProppantType               string    `json:"proppantType"`
	Range                      string    `json:"range"`
	RecoveryMethod             string    `json:"recoveryMethod"`
	RefracAdditiveVolume       float64   `json:"refracAdditiveVolume"`
	RefracClusterCount         float64   `json:"refracClusterCount"`
	RefracDate                 time.Time `json:"refracDate"` // time.Time if parsing as date
	RefracFluidVolume          float64   `json:"refracFluidVolume"`
	RefracFracVendor           string    `json:"refracFracVendor"`
	RefracMaxInjectionPressure float64   `json:"refracMaxInjectionPressure"`
	RefracMaxInjectionRate     float64   `json:"refracMaxInjectionRate"`
	RefracPropWeight           float64   `json:"refracPropWeight"`
	RefracStageCount           float64   `json:"refracStageCount"`
	RefracTreatmentType        string    `json:"refracTreatmentType"`
	Rig                        string    `json:"rig"`
	RS                         float64   `json:"rs"`
	RsegID                     string    `json:"rsegId"`
	Section                    string    `json:"section"`
	SG                         float64   `json:"sg"`
	SO                         float64   `json:"so"`
	SpudDate                   time.Time `json:"spudDate"` // time.Time if parsing as date
	StageSpacing               float64   `json:"stageSpacing"`
	State                      string    `json:"state"`
	Status                     string    `json:"status"`
	Subplay                    string    `json:"subplay"`
	SurfaceLatitude            float64   `json:"surfaceLatitude"`
	SurfaceLongitude           float64   `json:"surfaceLongitude"`
	Survey                     string    `json:"survey"`
	SW                         float64   `json:"sw"`
	TargetFormation            string    `json:"targetFormation"`
	TgsID                      string    `json:"tgsId"`
	Thickness                  float64   `json:"thickness"`
	TIL                        time.Time `json:"til"` // time.Time if parsing as date
	ToeInLandingZone           string    `json:"toeInLandingZone"`
	ToeLatitude                float64   `json:"toeLatitude"`
	ToeLongitude               float64   `json:"toeLongitude"`
	ToeUp                      string    `json:"toeUp"`
	Township                   string    `json:"township"`
	TrueVerticalDepth          float64   `json:"trueVerticalDepth"`
	TubingDepth                float64   `json:"tubingDepth"`
	TubingID                   float64   `json:"tubingId"`
	TypeCurveArea              string    `json:"typeCurveArea"`
	UpperPerforation           float64   `json:"upperPerforation"`
	VerticalSpacing            float64   `json:"verticalSpacing"`
	VtWellSpacingAnyZone       float64   `json:"vtWellSpacingAnyZone"`
	VtWellSpacingSameZone      float64   `json:"vtWellSpacingSameZone"`
	WellName                   string    `json:"wellName"`
	WellNumber                 string    `json:"wellNumber"`
	WellType                   string    `json:"wellType"`
	ZI                         float64   `json:"zi"`
}
